### ISSUE TITLE
Consider adding V to the Forest

### ISSUE THREAD

**Issue by rklaehn** [Actyx/banyan#23]
It seems like forest is emerging as just a convenient package of stuff (caches etc.). Maybe it is even more convenient to have V in there as well..

**Comment by rkuhn** [comment]
you mean “V for Vendetta”?

**Comment by rklaehn** [comment]
Surprised that anybody except for me reads these things. I mean V for Value. Currently a Forest does not care about the value, and a tree has the V type parameter. But it turns out that the individual tree is not that useful for what we want to do...

Just gonna try this out.
