### ISSUE TITLE
Use chacha instead of salsa

### ISSUE THREAD

**Issue by rklaehn** [Actyx/banyan#70]
It has a faster implementation, an IETF RFC https://tools.ietf.org/html/rfc7539 , and a security audit.

**Comment by rklaehn** [comment]
So we use a fixed nonce and a continuous 8 byte offset that is stored with the data to make the data self-contained.

The initial value of the offset when loading from disk is the offset + size of the root block, which in a content-addressed system is always the last written block.

**Comment by rkuhn** [comment]
“fixed nonce” is an oxymoron; I think we shouldn’t invest any more work in crypto before 2.0.0 is released.

**Comment by rklaehn** [comment]
Nothing wrong with a fixed nonce, as long as you use one key for one stream only. hypercore does this.
