### ISSUE TITLE
Provide way to differentiate level 0 and level>0 branches

### ISSUE THREAD

**Issue by rklaehn** [Actyx/banyan#87]
Level 0 branches contain the actual keys of a sequence, so they tend to be heavier than the higher level branches.

So in some cases it might be preferable to have a max_children of e.g. 32 for branches with level > 0 and 4 or even 1 for branches with level == 0.

Currently this is not possible.

**Comment by rkuhn** [comment]
Ah, now I understand: I always had the mental image of “level 0 branches” actually being the leaves, with one values block dangling off of each. So +1.

**Comment by rklaehn** [comment]
There are now 3 levels, values, keys, and summaries. Values are not branches but leaves, Keys are stored in the level 0 branches, summaries in levels >0.

I think this is the last thing that is obvious. Everything else will have to wait until we got better real world data to tune things...

**Comment by rklaehn** [comment]
https://github.com/Actyx/banyan/pull/89

**Comment by rklaehn** [comment]
https://github.com/Actyx/banyan/pull/90
